export enum ErrorHttp {
  ACOUNT_EXIST = 'ACOUNT_EXIST',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  EMAIL_NOEXITS = 'EMAIL_NO_EXITS',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
}
