export enum ErrorMessage {
  ACOUNT_EXIST = 'TAI KHOAN DA TON TAI',
  TOKEN_EXPIRED = 'TOKEN HET HAN',
  EMAIL_NOEXITS = 'EMAIL CHUA DANG KI',
  INCORRECT_PASSWORD = 'MAT KHAU KHONG DUNG',
  INTERNAL_SERVER_ERROR = 'LOI SERVER',
  NOT_FOUND = 'NOT_FOUND',
}
