export enum ErrorMessage {
  ACOUNT_EXIST = 'TAI KHOAN DA TON TAI',
  TOKEN_EXPIRED = 'TOKEN HET HAN',
  Unauthorized = 'LOI XAC THUC',
  EMAIL_NO_EXITS = 'EMAIL CHUA DANG KI',
  INCORRECT_PASSWORD = 'MAT KHAU KHONG DUNG',
  INTERNAL_SERVER_ERROR = 'LOI SERVER',
  NOT_FOUND = 'TAI NGUYEN KHONG TON TAI',
  BAD_REQUEST = 'YEU CAU KHONG HOP LE',
  CONFLICT = 'XUNG DOT DU LIEU',
  FORBIDDEN = 'KHONG CO QUYEN',
}
